#!/usr/bin/env python3
"""mpp — lightweight C++ library linker / CMake helper."""

from __future__ import annotations

import argparse
import platform
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from .build.cmake import ensure_cmake_links_package, generate_cmake
from .core import (
    VERSION,
    MppError,
    Project,
    detect_profile,
    ensure_dirs,
    git_head,
    load_project,
    load_toml,
    run,
    write_lock_toml,
    write_project_toml,
)
from .editor import ask_ide, generate_ide_config
from .recipes import (
    RECIPE_REPO_URL,
    find_recipe_and_version,
    recipe_commit,
    resolve_recipe_ref,
    select_recipe_platform,
    select_recipe_profile,
)
from .vendor import export_dependency, is_git_url


def init_cmd(args: argparse.Namespace) -> None:
    root = Path.cwd()
    ensure_dirs(root)
    ide = args.ide or ask_ide()
    config_path = root / "mpp.toml"
    if not config_path.exists():
        name = args.name or root.name.replace(" ", "-")
        write_project_toml(config_path, {
            "project": {"name": name, "version": "0.1.0", "cpp_standard": 20},
            "build": {"generator": "cmake", "build_dir": "build", "default_target": name, "build_type": "Debug", "export_compile_commands": True},
            "ide": {"name": ide},
            "dependencies": {},
        })
    lock = root / "mpp.lock"
    if not lock.exists():
        lock.write_text("# generated by mpp\n")
    cmake = root / "CMakeLists.txt"
    if args.cmake and not cmake.exists():
        name = args.name or root.name.replace(" ", "-")
        cmake.write_text(f"""cmake_minimum_required(VERSION 3.20)
project({name} LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

include(mpp/generated/mpp.cmake)

add_executable({name} src/main.cpp)
# mpp_link({name} package_name)
""")
        (root / "src").mkdir(exist_ok=True)
        main = root / "src" / "main.cpp"
        if not main.exists():
            main.write_text('#include <iostream>\n\nint main() {\n    std::cout << "hello from mpp\\n";\n}\n')
    project = Project(root, config_path, lock, load_toml(config_path))
    generate_cmake(project)
    generate_ide_config(project)
    print("initialized mpp project")


def print_recipe_options_cmd(args: argparse.Namespace) -> None:
    pkg, requested_version, recipe_path, recipe = find_recipe_and_version(args.package, args.version)
    version = requested_version or recipe.get("default_version", "HEAD")
    print(f"{pkg} {version}")
    print(f"recipe: {recipe_path}")

    versions = recipe.get("versions", {})
    if versions:
        print("\nversions:")
        for name in sorted(versions.keys()):
            print(f"  {name}")

    platforms = recipe.get("platforms", {}) or recipe.get("backends", {})
    if platforms:
        print("\nplatforms:")
        for name, meta in platforms.items():
            desc = meta.get("description", "")
            options = ", ".join(meta.get("options", []))
            suffix = f" - {desc}" if desc else ""
            print(f"  {name}{suffix}")
            if options:
                print(f"    options: {options}")

    options = recipe.get("options", {})
    if options:
        print("\noptions:")
        for name, meta in options.items():
            desc = meta.get("description", "")
            default = meta.get("default")
            values = meta.get("values", [])
            line = f"  {name}"
            if default is not None:
                line += f" (default: {default})"
            if desc:
                line += f" - {desc}"
            print(line)
            if values:
                print("    values: " + ", ".join(str(v) for v in values))

    if not platforms and not options:
        print("\nNo custom platform presets or options documented for this recipe.")


def add_cmd(args: argparse.Namespace) -> None:
    project = load_project()
    ensure_dirs(project.root)
    deps = project.config.setdefault("dependencies", {})

    if is_git_url(args.package):
        if args.platform or args.backend:
            raise MppError("--platform requires a named package recipe")
        pkg = args.package.rstrip("/").split("/")[-1].removesuffix(".git")
        git_url = args.package
        version = args.tag or args.branch or "HEAD"
        checkout_ref = args.tag or version
        checkout_branch = args.branch
        recipe: dict[str, Any] = {"name": pkg, "git": git_url, "default_version": version, "versions": {version: {}}}
        source = "git"
        recipe_rev = ""
    else:
        pkg, requested_version, recipe_path, recipe = find_recipe_and_version(args.package, args.version)
        git_url = recipe.get("git")
        if not git_url:
            raise MppError(f"recipe {pkg} missing git url")
        version = requested_version or recipe.get("default_version", "HEAD")
        checkout_ref, checkout_branch = resolve_recipe_ref(recipe, version)
        source = "recipe"
        recipe_rev = recipe_commit(recipe_path)

    user_options = (args.option or []) + (args.define or [])
    recipe_options = recipe.get("options", {})
    for opt in user_options:
        if "=" not in opt:
            raise MppError(f"option must be KEY=VALUE: {opt}")
        key, value = opt.split("=", 1)
        if key in recipe_options:
            values = [str(v) for v in recipe_options[key].get("values", [])]
            if values and value not in values:
                raise MppError(f"invalid value for {key}: {value}; valid: {', '.join(values)}")

    export_paths = recipe.get("export", {}).get("paths")
    commit = export_dependency(project.root, pkg, git_url, checkout_ref, checkout_branch, export_paths)
    deps[pkg] = {"version": version, "source": source}
    selected_platform = args.platform or args.backend
    if selected_platform:
        deps[pkg]["platform"] = selected_platform
    if user_options:
        deps[pkg]["options"] = user_options
    if source == "git":
        deps[pkg]["git"] = git_url
    write_project_toml(project.config_path, project.config)
    ensure_cmake_links_package(project.root, project.config, pkg)

    build_type = project.config.get("build", {}).get("build_type", "Debug")
    profile = detect_profile(build_type)
    lock_data = load_toml(project.lock_path).get("package", {})
    profile_meta = select_recipe_profile(recipe, profile)
    platform_meta = select_recipe_platform(recipe, selected_platform)
    cmake_meta = recipe.get("cmake", {})
    cmake_target = platform_meta.get("target") or cmake_meta.get("target") or recipe.get("target") or pkg
    cmake_source_dir = platform_meta.get("source_dir") or cmake_meta.get("source_dir", ".")
    cmake_options = cmake_meta.get("options", []) + platform_meta.get("options", []) + user_options
    include_dirs = profile_meta.get("include_dirs", ["include", "src"]) + platform_meta.get("include_dirs", [])
    system_libs = profile_meta.get("libs", []) + platform_meta.get("libs", [])
    lock_data[pkg] = {
        "version": version,
        "git": git_url,
        "commit": commit,
        "recipe_repo": RECIPE_REPO_URL,
        "recipe_commit": recipe_rev,
        "profile": profile,
        "cmake_target": cmake_target,
        "cmake_source_dir": cmake_source_dir,
        "cmake_options": cmake_options,
        "platform": selected_platform or "default",
        "include_dirs": list(dict.fromkeys(include_dirs)),
        "system_libs": list(dict.fromkeys(system_libs)),
    }
    write_lock_toml(project.lock_path, lock_data)
    updated_project = Project(project.root, project.config_path, project.lock_path, load_toml(project.config_path))
    generate_cmake(updated_project)
    generate_ide_config(updated_project)
    print(f"added {pkg}")


def build_cmd(args: argparse.Namespace) -> None:
    project = load_project()
    generate_cmake(project)
    build = project.config.get("build", {})
    build_dir = project.root / build.get("build_dir", "build")
    build_type = args.type or build.get("build_type", "Debug")
    generate_ide_config(project)
    run(["cmake", "-S", str(project.root), "-B", str(build_dir), f"-DCMAKE_BUILD_TYPE={build_type}", "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"])
    generate_ide_config(project)
    cmd = ["cmake", "--build", str(build_dir)]
    if args.target:
        cmd += ["--target", args.target]
    run(cmd)


def run_cmd(args: argparse.Namespace) -> None:
    project = load_project()
    build_cmd(argparse.Namespace(type=args.type, target=args.target))
    build = project.config.get("build", {})
    target = args.target or build.get("default_target") or project.config.get("project", {}).get("name")
    if not target:
        raise MppError("no target configured; use `mpp run <target>`")
    exe = project.root / build.get("build_dir", "build") / target
    if platform.system().lower() == "windows":
        exe = exe.with_suffix(".exe")
    if not exe.exists():
        candidates = list((project.root / build.get("build_dir", "build")).rglob(exe.name))
        if candidates:
            exe = candidates[0]
    if not exe.exists():
        raise MppError(f"built executable not found: {exe}")
    run([str(exe)] + args.args, cwd=project.root)


def clean_cmd(args: argparse.Namespace) -> None:
    project = load_project()
    build_dir = project.root / project.config.get("build", {}).get("build_dir", "build")
    for path in [build_dir, project.root / "mpp" / "generated"]:
        if path.exists():
            shutil.rmtree(path)
            print(f"removed {path}")
    if args.vendor:
        vend = project.root / "mpp" / "vendor"
        if vend.exists():
            shutil.rmtree(vend)
            print(f"removed {vend}")


def sync_cmd(args: argparse.Namespace) -> None:
    project = load_project()
    generate_cmake(project)
    generate_ide_config(project)
    print("generated mpp/generated/mpp.cmake")


def make_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="mpp", description="C++ module/package linker")
    p.add_argument("--version", action="version", version=f"mpp {VERSION}")
    sub = p.add_subparsers(dest="cmd", required=True)

    i = sub.add_parser("init", help="initialize project")
    i.add_argument("--name")
    i.add_argument("--ide", choices=["vscode", "clangd", "clion", "visualstudio", "generic", "all", "none", "nvim", "neovim", "vim", "zed", "sublime", "kate"], help="generate IDE/editor config")
    i.add_argument("--no-cmake", dest="cmake", action="store_false", help="do not create CMakeLists.txt")
    i.set_defaults(func=init_cmd, cmake=True)

    a = sub.add_parser("add", help="add package or git repo")
    a.add_argument("package")
    a.add_argument("--version")
    a.add_argument("--tag")
    a.add_argument("--branch")
    a.add_argument("--platform", help="select package platform preset, e.g. raylib --platform sdl")
    a.add_argument("--backend", help=argparse.SUPPRESS)
    a.add_argument("--option", action="append", metavar="KEY=VALUE", help="pass package CMake option; repeatable")
    a.add_argument("-D", "--define", action="append", metavar="KEY=VALUE", help="alias for --option; repeatable")
    a.set_defaults(func=add_cmd)

    o = sub.add_parser("options", help="show package versions, platforms, and options")
    o.add_argument("package")
    o.add_argument("--version")
    o.set_defaults(func=print_recipe_options_cmd)

    b = sub.add_parser("build", help="configure and build with CMake")
    b.add_argument("--type")
    b.add_argument("--target")
    b.set_defaults(func=build_cmd)

    r = sub.add_parser("run", help="build and run executable")
    r.add_argument("target", nargs="?")
    r.add_argument("--type")
    r.add_argument("args", nargs=argparse.REMAINDER)
    r.set_defaults(func=run_cmd)

    c = sub.add_parser("clean", help="remove build output")
    c.add_argument("--vendor", action="store_true")
    c.set_defaults(func=clean_cmd)

    s = sub.add_parser("sync", help="regenerate mpp files")
    s.set_defaults(func=sync_cmd)
    return p


def main(argv: list[str] | None = None) -> int:
    try:
        args = make_parser().parse_args(argv)
        args.func(args)
        return 0
    except MppError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as e:
        print(f"error: command failed with exit code {e.returncode}", file=sys.stderr)
        return e.returncode


if __name__ == "__main__":
    raise SystemExit(main())
